// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: converter.proto

package ru.tinkoff.hse.lib;

public final class Converter {
  private Converter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DecimalValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:converter.DecimalValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 scale = 1;</code>
     * @return The scale.
     */
    int getScale();

    /**
     * <code>uint32 precision = 2;</code>
     * @return The precision.
     */
    int getPrecision();

    /**
     * <code>bytes value = 3;</code>
     * @return The value.
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code converter.DecimalValue}
   */
  public static final class DecimalValue extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:converter.DecimalValue)
      DecimalValueOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DecimalValue.newBuilder() to construct.
    private DecimalValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DecimalValue() {
      value_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new DecimalValue();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Converter.internal_static_converter_DecimalValue_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Converter.internal_static_converter_DecimalValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Converter.DecimalValue.class, Converter.DecimalValue.Builder.class);
    }

    public static final int SCALE_FIELD_NUMBER = 1;
    private int scale_ = 0;
    /**
     * <code>uint32 scale = 1;</code>
     * @return The scale.
     */
    @Override
    public int getScale() {
      return scale_;
    }

    public static final int PRECISION_FIELD_NUMBER = 2;
    private int precision_ = 0;
    /**
     * <code>uint32 precision = 2;</code>
     * @return The precision.
     */
    @Override
    public int getPrecision() {
      return precision_;
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes value = 3;</code>
     * @return The value.
     */
    @Override
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (scale_ != 0) {
        output.writeUInt32(1, scale_);
      }
      if (precision_ != 0) {
        output.writeUInt32(2, precision_);
      }
      if (!value_.isEmpty()) {
        output.writeBytes(3, value_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (scale_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, scale_);
      }
      if (precision_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, precision_);
      }
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Converter.DecimalValue)) {
        return super.equals(obj);
      }
      Converter.DecimalValue other = (Converter.DecimalValue) obj;

      if (getScale()
          != other.getScale()) return false;
      if (getPrecision()
          != other.getPrecision()) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCALE_FIELD_NUMBER;
      hash = (53 * hash) + getScale();
      hash = (37 * hash) + PRECISION_FIELD_NUMBER;
      hash = (53 * hash) + getPrecision();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Converter.DecimalValue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Converter.DecimalValue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Converter.DecimalValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Converter.DecimalValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Converter.DecimalValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Converter.DecimalValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Converter.DecimalValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Converter.DecimalValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Converter.DecimalValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Converter.DecimalValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Converter.DecimalValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Converter.DecimalValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Converter.DecimalValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code converter.DecimalValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:converter.DecimalValue)
        Converter.DecimalValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Converter.internal_static_converter_DecimalValue_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Converter.internal_static_converter_DecimalValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Converter.DecimalValue.class, Converter.DecimalValue.Builder.class);
      }

      // Construct using converter.Converter.DecimalValue.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        scale_ = 0;
        precision_ = 0;
        value_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Converter.internal_static_converter_DecimalValue_descriptor;
      }

      @Override
      public Converter.DecimalValue getDefaultInstanceForType() {
        return Converter.DecimalValue.getDefaultInstance();
      }

      @Override
      public Converter.DecimalValue build() {
        Converter.DecimalValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Converter.DecimalValue buildPartial() {
        Converter.DecimalValue result = new Converter.DecimalValue(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Converter.DecimalValue result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.scale_ = scale_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.precision_ = precision_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.value_ = value_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Converter.DecimalValue) {
          return mergeFrom((Converter.DecimalValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Converter.DecimalValue other) {
        if (other == Converter.DecimalValue.getDefaultInstance()) return this;
        if (other.getScale() != 0) {
          setScale(other.getScale());
        }
        if (other.getPrecision() != 0) {
          setPrecision(other.getPrecision());
        }
        if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                scale_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                precision_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                value_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int scale_ ;
      /**
       * <code>uint32 scale = 1;</code>
       * @return The scale.
       */
      @Override
      public int getScale() {
        return scale_;
      }
      /**
       * <code>uint32 scale = 1;</code>
       * @param value The scale to set.
       * @return This builder for chaining.
       */
      public Builder setScale(int value) {

        scale_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 scale = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearScale() {
        bitField0_ = (bitField0_ & ~0x00000001);
        scale_ = 0;
        onChanged();
        return this;
      }

      private int precision_ ;
      /**
       * <code>uint32 precision = 2;</code>
       * @return The precision.
       */
      @Override
      public int getPrecision() {
        return precision_;
      }
      /**
       * <code>uint32 precision = 2;</code>
       * @param value The precision to set.
       * @return This builder for chaining.
       */
      public Builder setPrecision(int value) {

        precision_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 precision = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrecision() {
        bitField0_ = (bitField0_ & ~0x00000002);
        precision_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes value = 3;</code>
       * @return The value.
       */
      @Override
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>bytes value = 3;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bytes value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:converter.DecimalValue)
    }

    // @@protoc_insertion_point(class_scope:converter.DecimalValue)
    private static final Converter.DecimalValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Converter.DecimalValue();
    }

    public static Converter.DecimalValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DecimalValue>
        PARSER = new com.google.protobuf.AbstractParser<DecimalValue>() {
      @Override
      public DecimalValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DecimalValue> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DecimalValue> getParserForType() {
      return PARSER;
    }

    @Override
    public Converter.DecimalValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConvertRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:converter.ConvertRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string from_currency = 1;</code>
     * @return The fromCurrency.
     */
    String getFromCurrency();
    /**
     * <code>string from_currency = 1;</code>
     * @return The bytes for fromCurrency.
     */
    com.google.protobuf.ByteString
        getFromCurrencyBytes();

    /**
     * <code>string to_currency = 2;</code>
     * @return The toCurrency.
     */
    String getToCurrency();
    /**
     * <code>string to_currency = 2;</code>
     * @return The bytes for toCurrency.
     */
    com.google.protobuf.ByteString
        getToCurrencyBytes();

    /**
     * <code>.converter.DecimalValue amount = 3;</code>
     * @return Whether the amount field is set.
     */
    boolean hasAmount();
    /**
     * <code>.converter.DecimalValue amount = 3;</code>
     * @return The amount.
     */
    Converter.DecimalValue getAmount();
    /**
     * <code>.converter.DecimalValue amount = 3;</code>
     */
    Converter.DecimalValueOrBuilder getAmountOrBuilder();
  }
  /**
   * Protobuf type {@code converter.ConvertRequest}
   */
  public static final class ConvertRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:converter.ConvertRequest)
      ConvertRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConvertRequest.newBuilder() to construct.
    private ConvertRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConvertRequest() {
      fromCurrency_ = "";
      toCurrency_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConvertRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Converter.internal_static_converter_ConvertRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Converter.internal_static_converter_ConvertRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Converter.ConvertRequest.class, Converter.ConvertRequest.Builder.class);
    }

    public static final int FROM_CURRENCY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object fromCurrency_ = "";
    /**
     * <code>string from_currency = 1;</code>
     * @return The fromCurrency.
     */
    @Override
    public String getFromCurrency() {
      Object ref = fromCurrency_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fromCurrency_ = s;
        return s;
      }
    }
    /**
     * <code>string from_currency = 1;</code>
     * @return The bytes for fromCurrency.
     */
    @Override
    public com.google.protobuf.ByteString
        getFromCurrencyBytes() {
      Object ref = fromCurrency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fromCurrency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_CURRENCY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object toCurrency_ = "";
    /**
     * <code>string to_currency = 2;</code>
     * @return The toCurrency.
     */
    @Override
    public String getToCurrency() {
      Object ref = toCurrency_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        toCurrency_ = s;
        return s;
      }
    }
    /**
     * <code>string to_currency = 2;</code>
     * @return The bytes for toCurrency.
     */
    @Override
    public com.google.protobuf.ByteString
        getToCurrencyBytes() {
      Object ref = toCurrency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        toCurrency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private Converter.DecimalValue amount_;
    /**
     * <code>.converter.DecimalValue amount = 3;</code>
     * @return Whether the amount field is set.
     */
    @Override
    public boolean hasAmount() {
      return amount_ != null;
    }
    /**
     * <code>.converter.DecimalValue amount = 3;</code>
     * @return The amount.
     */
    @Override
    public Converter.DecimalValue getAmount() {
      return amount_ == null ? Converter.DecimalValue.getDefaultInstance() : amount_;
    }
    /**
     * <code>.converter.DecimalValue amount = 3;</code>
     */
    @Override
    public Converter.DecimalValueOrBuilder getAmountOrBuilder() {
      return amount_ == null ? Converter.DecimalValue.getDefaultInstance() : amount_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromCurrency_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fromCurrency_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(toCurrency_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, toCurrency_);
      }
      if (amount_ != null) {
        output.writeMessage(3, getAmount());
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromCurrency_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fromCurrency_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(toCurrency_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, toCurrency_);
      }
      if (amount_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getAmount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Converter.ConvertRequest)) {
        return super.equals(obj);
      }
      Converter.ConvertRequest other = (Converter.ConvertRequest) obj;

      if (!getFromCurrency()
          .equals(other.getFromCurrency())) return false;
      if (!getToCurrency()
          .equals(other.getToCurrency())) return false;
      if (hasAmount() != other.hasAmount()) return false;
      if (hasAmount()) {
        if (!getAmount()
            .equals(other.getAmount())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + getFromCurrency().hashCode();
      hash = (37 * hash) + TO_CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + getToCurrency().hashCode();
      if (hasAmount()) {
        hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getAmount().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Converter.ConvertRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Converter.ConvertRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Converter.ConvertRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Converter.ConvertRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Converter.ConvertRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Converter.ConvertRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Converter.ConvertRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Converter.ConvertRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Converter.ConvertRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Converter.ConvertRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Converter.ConvertRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Converter.ConvertRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Converter.ConvertRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code converter.ConvertRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:converter.ConvertRequest)
        Converter.ConvertRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Converter.internal_static_converter_ConvertRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Converter.internal_static_converter_ConvertRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Converter.ConvertRequest.class, Converter.ConvertRequest.Builder.class);
      }

      // Construct using converter.Converter.ConvertRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fromCurrency_ = "";
        toCurrency_ = "";
        amount_ = null;
        if (amountBuilder_ != null) {
          amountBuilder_.dispose();
          amountBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Converter.internal_static_converter_ConvertRequest_descriptor;
      }

      @Override
      public Converter.ConvertRequest getDefaultInstanceForType() {
        return Converter.ConvertRequest.getDefaultInstance();
      }

      @Override
      public Converter.ConvertRequest build() {
        Converter.ConvertRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Converter.ConvertRequest buildPartial() {
        Converter.ConvertRequest result = new Converter.ConvertRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Converter.ConvertRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fromCurrency_ = fromCurrency_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.toCurrency_ = toCurrency_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.amount_ = amountBuilder_ == null
              ? amount_
              : amountBuilder_.build();
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Converter.ConvertRequest) {
          return mergeFrom((Converter.ConvertRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Converter.ConvertRequest other) {
        if (other == Converter.ConvertRequest.getDefaultInstance()) return this;
        if (!other.getFromCurrency().isEmpty()) {
          fromCurrency_ = other.fromCurrency_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getToCurrency().isEmpty()) {
          toCurrency_ = other.toCurrency_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasAmount()) {
          mergeAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                fromCurrency_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                toCurrency_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getAmountFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object fromCurrency_ = "";
      /**
       * <code>string from_currency = 1;</code>
       * @return The fromCurrency.
       */
      public String getFromCurrency() {
        Object ref = fromCurrency_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fromCurrency_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string from_currency = 1;</code>
       * @return The bytes for fromCurrency.
       */
      public com.google.protobuf.ByteString
          getFromCurrencyBytes() {
        Object ref = fromCurrency_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fromCurrency_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string from_currency = 1;</code>
       * @param value The fromCurrency to set.
       * @return This builder for chaining.
       */
      public Builder setFromCurrency(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        fromCurrency_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string from_currency = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromCurrency() {
        fromCurrency_ = getDefaultInstance().getFromCurrency();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string from_currency = 1;</code>
       * @param value The bytes for fromCurrency to set.
       * @return This builder for chaining.
       */
      public Builder setFromCurrencyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fromCurrency_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object toCurrency_ = "";
      /**
       * <code>string to_currency = 2;</code>
       * @return The toCurrency.
       */
      public String getToCurrency() {
        Object ref = toCurrency_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          toCurrency_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string to_currency = 2;</code>
       * @return The bytes for toCurrency.
       */
      public com.google.protobuf.ByteString
          getToCurrencyBytes() {
        Object ref = toCurrency_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          toCurrency_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string to_currency = 2;</code>
       * @param value The toCurrency to set.
       * @return This builder for chaining.
       */
      public Builder setToCurrency(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        toCurrency_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string to_currency = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToCurrency() {
        toCurrency_ = getDefaultInstance().getToCurrency();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string to_currency = 2;</code>
       * @param value The bytes for toCurrency to set.
       * @return This builder for chaining.
       */
      public Builder setToCurrencyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        toCurrency_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private Converter.DecimalValue amount_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Converter.DecimalValue, Converter.DecimalValue.Builder, Converter.DecimalValueOrBuilder> amountBuilder_;
      /**
       * <code>.converter.DecimalValue amount = 3;</code>
       * @return Whether the amount field is set.
       */
      public boolean hasAmount() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.converter.DecimalValue amount = 3;</code>
       * @return The amount.
       */
      public Converter.DecimalValue getAmount() {
        if (amountBuilder_ == null) {
          return amount_ == null ? Converter.DecimalValue.getDefaultInstance() : amount_;
        } else {
          return amountBuilder_.getMessage();
        }
      }
      /**
       * <code>.converter.DecimalValue amount = 3;</code>
       */
      public Builder setAmount(Converter.DecimalValue value) {
        if (amountBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          amount_ = value;
        } else {
          amountBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.converter.DecimalValue amount = 3;</code>
       */
      public Builder setAmount(
          Converter.DecimalValue.Builder builderForValue) {
        if (amountBuilder_ == null) {
          amount_ = builderForValue.build();
        } else {
          amountBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.converter.DecimalValue amount = 3;</code>
       */
      public Builder mergeAmount(Converter.DecimalValue value) {
        if (amountBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            amount_ != null &&
            amount_ != Converter.DecimalValue.getDefaultInstance()) {
            getAmountBuilder().mergeFrom(value);
          } else {
            amount_ = value;
          }
        } else {
          amountBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.converter.DecimalValue amount = 3;</code>
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        amount_ = null;
        if (amountBuilder_ != null) {
          amountBuilder_.dispose();
          amountBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.converter.DecimalValue amount = 3;</code>
       */
      public Converter.DecimalValue.Builder getAmountBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getAmountFieldBuilder().getBuilder();
      }
      /**
       * <code>.converter.DecimalValue amount = 3;</code>
       */
      public Converter.DecimalValueOrBuilder getAmountOrBuilder() {
        if (amountBuilder_ != null) {
          return amountBuilder_.getMessageOrBuilder();
        } else {
          return amount_ == null ?
              Converter.DecimalValue.getDefaultInstance() : amount_;
        }
      }
      /**
       * <code>.converter.DecimalValue amount = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Converter.DecimalValue, Converter.DecimalValue.Builder, Converter.DecimalValueOrBuilder>
          getAmountFieldBuilder() {
        if (amountBuilder_ == null) {
          amountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Converter.DecimalValue, Converter.DecimalValue.Builder, Converter.DecimalValueOrBuilder>(
                  getAmount(),
                  getParentForChildren(),
                  isClean());
          amount_ = null;
        }
        return amountBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:converter.ConvertRequest)
    }

    // @@protoc_insertion_point(class_scope:converter.ConvertRequest)
    private static final Converter.ConvertRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Converter.ConvertRequest();
    }

    public static Converter.ConvertRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConvertRequest>
        PARSER = new com.google.protobuf.AbstractParser<ConvertRequest>() {
      @Override
      public ConvertRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ConvertRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ConvertRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public Converter.ConvertRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConvertResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:converter.ConvertResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string currency = 1;</code>
     * @return The currency.
     */
    String getCurrency();
    /**
     * <code>string currency = 1;</code>
     * @return The bytes for currency.
     */
    com.google.protobuf.ByteString
        getCurrencyBytes();

    /**
     * <code>.converter.DecimalValue converted_amount = 2;</code>
     * @return Whether the convertedAmount field is set.
     */
    boolean hasConvertedAmount();
    /**
     * <code>.converter.DecimalValue converted_amount = 2;</code>
     * @return The convertedAmount.
     */
    Converter.DecimalValue getConvertedAmount();
    /**
     * <code>.converter.DecimalValue converted_amount = 2;</code>
     */
    Converter.DecimalValueOrBuilder getConvertedAmountOrBuilder();
  }
  /**
   * Protobuf type {@code converter.ConvertResponse}
   */
  public static final class ConvertResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:converter.ConvertResponse)
      ConvertResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConvertResponse.newBuilder() to construct.
    private ConvertResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConvertResponse() {
      currency_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConvertResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Converter.internal_static_converter_ConvertResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Converter.internal_static_converter_ConvertResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Converter.ConvertResponse.class, Converter.ConvertResponse.Builder.class);
    }

    public static final int CURRENCY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object currency_ = "";
    /**
     * <code>string currency = 1;</code>
     * @return The currency.
     */
    @Override
    public String getCurrency() {
      Object ref = currency_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      }
    }
    /**
     * <code>string currency = 1;</code>
     * @return The bytes for currency.
     */
    @Override
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      Object ref = currency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONVERTED_AMOUNT_FIELD_NUMBER = 2;
    private Converter.DecimalValue convertedAmount_;
    /**
     * <code>.converter.DecimalValue converted_amount = 2;</code>
     * @return Whether the convertedAmount field is set.
     */
    @Override
    public boolean hasConvertedAmount() {
      return convertedAmount_ != null;
    }
    /**
     * <code>.converter.DecimalValue converted_amount = 2;</code>
     * @return The convertedAmount.
     */
    @Override
    public Converter.DecimalValue getConvertedAmount() {
      return convertedAmount_ == null ? Converter.DecimalValue.getDefaultInstance() : convertedAmount_;
    }
    /**
     * <code>.converter.DecimalValue converted_amount = 2;</code>
     */
    @Override
    public Converter.DecimalValueOrBuilder getConvertedAmountOrBuilder() {
      return convertedAmount_ == null ? Converter.DecimalValue.getDefaultInstance() : convertedAmount_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currency_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currency_);
      }
      if (convertedAmount_ != null) {
        output.writeMessage(2, getConvertedAmount());
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currency_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currency_);
      }
      if (convertedAmount_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getConvertedAmount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Converter.ConvertResponse)) {
        return super.equals(obj);
      }
      Converter.ConvertResponse other = (Converter.ConvertResponse) obj;

      if (!getCurrency()
          .equals(other.getCurrency())) return false;
      if (hasConvertedAmount() != other.hasConvertedAmount()) return false;
      if (hasConvertedAmount()) {
        if (!getConvertedAmount()
            .equals(other.getConvertedAmount())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + getCurrency().hashCode();
      if (hasConvertedAmount()) {
        hash = (37 * hash) + CONVERTED_AMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getConvertedAmount().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Converter.ConvertResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Converter.ConvertResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Converter.ConvertResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Converter.ConvertResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Converter.ConvertResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Converter.ConvertResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Converter.ConvertResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Converter.ConvertResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Converter.ConvertResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Converter.ConvertResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Converter.ConvertResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Converter.ConvertResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Converter.ConvertResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code converter.ConvertResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:converter.ConvertResponse)
        Converter.ConvertResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Converter.internal_static_converter_ConvertResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Converter.internal_static_converter_ConvertResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Converter.ConvertResponse.class, Converter.ConvertResponse.Builder.class);
      }

      // Construct using converter.Converter.ConvertResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        currency_ = "";
        convertedAmount_ = null;
        if (convertedAmountBuilder_ != null) {
          convertedAmountBuilder_.dispose();
          convertedAmountBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Converter.internal_static_converter_ConvertResponse_descriptor;
      }

      @Override
      public Converter.ConvertResponse getDefaultInstanceForType() {
        return Converter.ConvertResponse.getDefaultInstance();
      }

      @Override
      public Converter.ConvertResponse build() {
        Converter.ConvertResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Converter.ConvertResponse buildPartial() {
        Converter.ConvertResponse result = new Converter.ConvertResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Converter.ConvertResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.currency_ = currency_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.convertedAmount_ = convertedAmountBuilder_ == null
              ? convertedAmount_
              : convertedAmountBuilder_.build();
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Converter.ConvertResponse) {
          return mergeFrom((Converter.ConvertResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Converter.ConvertResponse other) {
        if (other == Converter.ConvertResponse.getDefaultInstance()) return this;
        if (!other.getCurrency().isEmpty()) {
          currency_ = other.currency_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasConvertedAmount()) {
          mergeConvertedAmount(other.getConvertedAmount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                currency_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getConvertedAmountFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object currency_ = "";
      /**
       * <code>string currency = 1;</code>
       * @return The currency.
       */
      public String getCurrency() {
        Object ref = currency_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          currency_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string currency = 1;</code>
       * @return The bytes for currency.
       */
      public com.google.protobuf.ByteString
          getCurrencyBytes() {
        Object ref = currency_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          currency_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currency = 1;</code>
       * @param value The currency to set.
       * @return This builder for chaining.
       */
      public Builder setCurrency(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        currency_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string currency = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrency() {
        currency_ = getDefaultInstance().getCurrency();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string currency = 1;</code>
       * @param value The bytes for currency to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        currency_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Converter.DecimalValue convertedAmount_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Converter.DecimalValue, Converter.DecimalValue.Builder, Converter.DecimalValueOrBuilder> convertedAmountBuilder_;
      /**
       * <code>.converter.DecimalValue converted_amount = 2;</code>
       * @return Whether the convertedAmount field is set.
       */
      public boolean hasConvertedAmount() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.converter.DecimalValue converted_amount = 2;</code>
       * @return The convertedAmount.
       */
      public Converter.DecimalValue getConvertedAmount() {
        if (convertedAmountBuilder_ == null) {
          return convertedAmount_ == null ? Converter.DecimalValue.getDefaultInstance() : convertedAmount_;
        } else {
          return convertedAmountBuilder_.getMessage();
        }
      }
      /**
       * <code>.converter.DecimalValue converted_amount = 2;</code>
       */
      public Builder setConvertedAmount(Converter.DecimalValue value) {
        if (convertedAmountBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          convertedAmount_ = value;
        } else {
          convertedAmountBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.converter.DecimalValue converted_amount = 2;</code>
       */
      public Builder setConvertedAmount(
          Converter.DecimalValue.Builder builderForValue) {
        if (convertedAmountBuilder_ == null) {
          convertedAmount_ = builderForValue.build();
        } else {
          convertedAmountBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.converter.DecimalValue converted_amount = 2;</code>
       */
      public Builder mergeConvertedAmount(Converter.DecimalValue value) {
        if (convertedAmountBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            convertedAmount_ != null &&
            convertedAmount_ != Converter.DecimalValue.getDefaultInstance()) {
            getConvertedAmountBuilder().mergeFrom(value);
          } else {
            convertedAmount_ = value;
          }
        } else {
          convertedAmountBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.converter.DecimalValue converted_amount = 2;</code>
       */
      public Builder clearConvertedAmount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        convertedAmount_ = null;
        if (convertedAmountBuilder_ != null) {
          convertedAmountBuilder_.dispose();
          convertedAmountBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.converter.DecimalValue converted_amount = 2;</code>
       */
      public Converter.DecimalValue.Builder getConvertedAmountBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getConvertedAmountFieldBuilder().getBuilder();
      }
      /**
       * <code>.converter.DecimalValue converted_amount = 2;</code>
       */
      public Converter.DecimalValueOrBuilder getConvertedAmountOrBuilder() {
        if (convertedAmountBuilder_ != null) {
          return convertedAmountBuilder_.getMessageOrBuilder();
        } else {
          return convertedAmount_ == null ?
              Converter.DecimalValue.getDefaultInstance() : convertedAmount_;
        }
      }
      /**
       * <code>.converter.DecimalValue converted_amount = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Converter.DecimalValue, Converter.DecimalValue.Builder, Converter.DecimalValueOrBuilder>
          getConvertedAmountFieldBuilder() {
        if (convertedAmountBuilder_ == null) {
          convertedAmountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Converter.DecimalValue, Converter.DecimalValue.Builder, Converter.DecimalValueOrBuilder>(
                  getConvertedAmount(),
                  getParentForChildren(),
                  isClean());
          convertedAmount_ = null;
        }
        return convertedAmountBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:converter.ConvertResponse)
    }

    // @@protoc_insertion_point(class_scope:converter.ConvertResponse)
    private static final Converter.ConvertResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Converter.ConvertResponse();
    }

    public static Converter.ConvertResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConvertResponse>
        PARSER = new com.google.protobuf.AbstractParser<ConvertResponse>() {
      @Override
      public ConvertResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ConvertResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ConvertResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public Converter.ConvertResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_converter_DecimalValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_converter_DecimalValue_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_converter_ConvertRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_converter_ConvertRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_converter_ConvertResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_converter_ConvertResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017converter.proto\022\tconverter\"?\n\014DecimalV" +
      "alue\022\r\n\005scale\030\001 \001(\r\022\021\n\tprecision\030\002 \001(\r\022\r" +
      "\n\005value\030\003 \001(\014\"e\n\016ConvertRequest\022\025\n\rfrom_" +
      "currency\030\001 \001(\t\022\023\n\013to_currency\030\002 \001(\t\022\'\n\006a" +
      "mount\030\003 \001(\0132\027.converter.DecimalValue\"V\n\017" +
      "ConvertResponse\022\020\n\010currency\030\001 \001(\t\0221\n\020con" +
      "verted_amount\030\002 \001(\0132\027.converter.DecimalV" +
      "alue2U\n\021CurrencyConverter\022@\n\007Convert\022\031.c" +
      "onverter.ConvertRequest\032\032.converter.Conv" +
      "ertResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_converter_DecimalValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_converter_DecimalValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_converter_DecimalValue_descriptor,
        new String[] { "Scale", "Precision", "Value", });
    internal_static_converter_ConvertRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_converter_ConvertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_converter_ConvertRequest_descriptor,
        new String[] { "FromCurrency", "ToCurrency", "Amount", });
    internal_static_converter_ConvertResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_converter_ConvertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_converter_ConvertResponse_descriptor,
        new String[] { "Currency", "ConvertedAmount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
