// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: converter.proto

package ru.tinkoff.hse.lib;

public interface ConvertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:converter.ConvertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string currency = 1;</code>
   * @return The currency.
   */
  java.lang.String getCurrency();
  /**
   * <code>string currency = 1;</code>
   * @return The bytes for currency.
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <code>string converted_amount = 2;</code>
   * @return The convertedAmount.
   */
  java.lang.String getConvertedAmount();
  /**
   * <code>string converted_amount = 2;</code>
   * @return The bytes for convertedAmount.
   */
  com.google.protobuf.ByteString
      getConvertedAmountBytes();
}
