// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: converter.proto

package ru.tinkoff.hse.lib;

public final class Converter {
  private Converter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_converter_ConvertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_converter_ConvertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_converter_ConvertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_converter_ConvertResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017converter.proto\022\tconverter\"L\n\016ConvertR" +
      "equest\022\025\n\rfrom_currency\030\001 \001(\t\022\023\n\013to_curr" +
      "ency\030\002 \001(\t\022\016\n\006amount\030\003 \001(\t\"=\n\017ConvertRes" +
      "ponse\022\020\n\010currency\030\001 \001(\t\022\030\n\020converted_amo" +
      "unt\030\002 \001(\t2U\n\021CurrencyConverter\022@\n\007Conver" +
      "t\022\031.converter.ConvertRequest\032\032.converter" +
      ".ConvertResponseB \n\034ru.tinkoff.hse.lib.c" +
      "onverterP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_converter_ConvertRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_converter_ConvertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_converter_ConvertRequest_descriptor,
        new java.lang.String[] { "FromCurrency", "ToCurrency", "Amount", });
    internal_static_converter_ConvertResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_converter_ConvertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_converter_ConvertResponse_descriptor,
        new java.lang.String[] { "Currency", "ConvertedAmount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
