apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-hw2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helm-hw2
  template:
    metadata:
      labels:
        app: helm-hw2
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080