management:
  endpoint:
    health:
      probes:
        enabled: true

app:
  rates-url: ${RATES_URL:http://rates:8080/rates}
  keycloak-url: ${KEYCLOAK_URL}
  keycloak-realm: ${KEYCLOAK_REALM}
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}