replicaCount: 2

image:
  repository: avdm2/tinkoff_hw3
  pullPolicy: IfNotPresent
  tag: latest

extraEnv: {}

fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 30
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 30