replicaCount: 3

image:
  repository: avdm2/tinkoff_hw2
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

serviceAccount:
  create: true
  automount: true

ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
