  name: Docker Image CI

  on:
    push:
      branches:
        - main
    pull_request:
      types: [opened, reopened]
      branches:
        - main

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Java + Maven
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'

        - name: Maven clean install
          run: mvn clean install

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push the Docker Image
          run: |
            docker build --build-arg JAR_FILE=target/\*.jar --tag ${{ secrets.DOCKER_USERNAME }}/tinkoff_hw1:${GITHUB_REF_NAME//\//-}-${GITHUB_SHA::7} .
            docker push ${{ secrets.DOCKER_USERNAME }}/tinkoff_hw1:${GITHUB_REF_NAME//\//-}-${GITHUB_SHA::7}

        - name: Push latest
          if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          run: |
            docker tag ${{ secrets.DOCKER_USERNAME }}/tinkoff_hw1:${GITHUB_REF_NAME//\//-}-${GITHUB_SHA::7} ${{ secrets.DOCKER_USERNAME }}/tinkoff_hw1:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/tinkoff_hw1:latest
