name: Docker Image CI

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - main
      - feedback

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java + Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Maven clean install
        run: mvn clean install

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker Image
        run: |
          docker build --build-arg JAR_FILE=target/\*.jar --tag ${{ secrets.DOCKER_USERNAME }}/tinkoff_hw3:${GITHUB_REF_NAME//\//-}-${GITHUB_SHA::7} .
          docker push ${{ secrets.DOCKER_USERNAME }}/tinkoff_hw3:${GITHUB_REF_NAME//\//-}-${GITHUB_SHA::7}

      - name: Push latest
        if: ${{ github.ref_name == 'main' }}
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/tinkoff_hw3:${GITHUB_REF_NAME//\//-}-${GITHUB_SHA::7} ${{ secrets.DOCKER_USERNAME }}/tinkoff_hw3:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/tinkoff_hw3:latest

  autotest:
    needs: build
    uses: central-university-dev/hse-ab-cicd-hw/.github/workflows/autotests.yml@main
    with:
      chart-path: ./helm-hw2
      image-name: avdm2/tinkoff_hw3
      image-tag: ${GITHUB_REF_NAME//\//-}-${GITHUB_SHA::7}